### ISSUE TITLE
Column length too big for column 'body' (max = 21845); use BLOB or TEXT instead 

### ISSUE THREAD

**Issue by semanticart** [BrianTheCoder/dm-is-schemaless#1]
I'm running the specs against mysql and after creating the schemaless_test database, the specs are throwing:  "Column length too big for column 'body' (max = 21845); use BLOB or TEXT instead"

This occurs on every spec, here's an example trace:

<pre>
8)
DataObjects::SQLError in 'DataMapper::Is::Schemaless structure has the property id'
Column length too big for column 'body' (max = 21845); use BLOB or TEXT instead
/Library/Ruby/Gems/1.8/gems/dm-core-0.10.1/lib/dm-core/migrations.rb:147:in `execute_non_query'
/Library/Ruby/Gems/1.8/gems/dm-core-0.10.1/lib/dm-core/migrations.rb:147:in `create_model_storage'
/Library/Ruby/Gems/1.8/gems/dm-core-0.10.1/lib/dm-core/adapters/data_objects_adapter.rb:266:in `with_connection'
/Library/Ruby/Gems/1.8/gems/dm-core-0.10.1/lib/dm-core/migrations.rb:144:in `create_model_storage'
/Library/Ruby/Gems/1.8/gems/dm-core-0.10.1/lib/dm-core/migrations.rb:1166:in `create_model_storage'
/Library/Ruby/Gems/1.8/gems/dm-core-0.10.1/lib/dm-core/migrations.rb:1260:in `auto_migrate_up!'
/Library/Ruby/Gems/1.8/gems/dm-core-0.10.1/lib/dm-core/migrations.rb:49:in `send'
/Library/Ruby/Gems/1.8/gems/dm-core-0.10.1/lib/dm-core/migrations.rb:49:in `repository_execute'
/Library/Ruby/Gems/1.8/gems/dm-core-0.10.1/lib/dm-core/model/descendant_set.rb:33:in `each'
/Library/Ruby/Gems/1.8/gems/dm-core-0.10.1/lib/dm-core/model/descendant_set.rb:33:in `each'
/Library/Ruby/Gems/1.8/gems/dm-core-0.10.1/lib/dm-core/migrations.rb:48:in `repository_execute'
/Library/Ruby/Gems/1.8/gems/dm-core-0.10.1/lib/dm-core/migrations.rb:42:in `auto_migrate_up!'
/Library/Ruby/Gems/1.8/gems/dm-core-0.10.1/lib/dm-core/migrations.rb:22:in `auto_migrate!'
./spec/integration/schemaless_spec.rb:10:
</pre>

I'm guessing this is related to   property :body, DataMapper::Types::Json, :default => {} but I don't know enough about DataMapper::Types::Json to know what if any changes need to be made.

**Comment by BrianTheCoder** [comment]
Fixed in http://datamapper.lighthouseapp.com/projects/20609/tickets/999-dm-types-yaml-reverted-to-using-string-rather-than-text-type
